### ISSUE TITLE
Transport connection broken when uploading file

### ISSUE THREAD

**Issue by aleproust** [jcmturner/gokrb5#283] opened 2019-05-01 12:48 UTC
Hello,
First, thanks for the kerberos authentication library.
I use it to on client side and I have no problem to authenticate. 

My issue is more when I want to upload a file. An http error occurs and I don't really know where it comes from. It works well when I process a GET on the same path. 

```
func main() {
	cfg, err := config.Load("./krb5.conf")

	if err != nil {
		println("ERROR!")
	}
        kt, err := keytab.Load("./mykeytab.keytab")
        cl := client.NewClientWithKeytab("user", "DOMAIN", kt, cfg, client.DisablePAFXFAST(true))
        r, _ := http.NewRequest("PUT", "http://kerbyserver/webhdfs/v1/data/the/path/12345?op=CREATE&data=true&overwrite=true&createparent=true&user.name=user", body)
        r.Header.Add("Content-Type", "application/octet-stream")
        spnegoCl := spnego.NewClient(cl, nil, "")
        resp, err := spnegoCl.Do(r)

	if err != nil {
		panic(err)
	}
	budy, _ := ioutil.ReadAll(resp.Body)
	fmt.Printf("%s", budy)

}
```

Error 
```
HTTP/1.x transport connection broken: http: ContentLength=8 with Body length 0
```

It works well when uploading EMPTY files

When I process it via curl, on the same machine, there is no problem and the upload process full completes

Thank you

**Comment by jcmturner** [comment] 2019-05-05 13:40
@aleproust I'm not sure what the issue is here. There is a test for upload:

https://github.com/jcmturner/gokrb5/blob/7b6b2f54b7fda31a47cd7e68ca8485dedeb0e1ed/spnego/http_test.go#L250

To troubleshoot can you get a tcpdump when using your client and when using curl and compare?

**Comment by aleproust** [comment] 2019-05-06 18:58
Hello,
On our side we did tests to compare, bellow the results.

With curl:
```
curl -ivv --negotiate -u: -XPUT "http://hadoop-host:50070/webhdfs/v1/user/<redacted>/test?op=CREATE&overwrite=true&createparent=true&user.name=<redacted>&data=true"  -T test_file -H 'Content-Type: application/octet-stream'
*   Trying <IP ADDR>...
* TCP_NODELAY set
* Connected to hadoop-host (<IP ADDR>) port 50070 (#0)
> PUT /webhdfs/v1/user/<redacted>/test?op=CREATE&overwrite=true&createparent=true&user.name=<redacted>&data=true HTTP/1.1
> Host: hadoop-host:50070
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/octet-stream
> Content-Length: 15
> Expect: 100-continue
>
< HTTP/1.1 401 Authentication required
HTTP/1.1 401 Authentication required
< Date: Mon, 06 May 2019 18:20:57 GMT
Date: Mon, 06 May 2019 18:20:57 GMT
< Date: Mon, 06 May 2019 18:20:57 GMT
Date: Mon, 06 May 2019 18:20:57 GMT
< Pragma: no-cache
Pragma: no-cache
< X-FRAME-OPTIONS: SAMEORIGIN
X-FRAME-OPTIONS: SAMEORIGIN
< WWW-Authenticate: Negotiate
WWW-Authenticate: Negotiate
< Set-Cookie: hadoop.auth=; Path=/; HttpOnly
Set-Cookie: hadoop.auth=; Path=/; HttpOnly
< Content-Length: 0
Content-Length: 0
< Connection: close
Connection: close

<
* Closing connection 0
* Issue another request to this URL: 'http://hadoop-host:50070/webhdfs/v1/user/<redacted>/test?op=CREATE&overwrite=true&createparent=true&user.name=<redacted>&data=true'
* Hostname hadoop-host was found in DNS cache
*   Trying <IP ADDR>...
* TCP_NODELAY set
* Connected to hadoop-host (<IP ADDR>) port 50070 (#1)
* Server auth using Negotiate with user ''
> PUT /webhdfs/v1/user/<redacted>/test?op=CREATE&overwrite=true&createparent=true&user.name=<redacted>&data=true HTTP/1.1
> Host: hadoop-host:50070
> Authorization: Negotiate <TOKEN>
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/octet-stream
> Content-Length: 15
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

* We are completely uploaded and fine
```
With gokrb5:
```
PUT /webhdfs/v1/user/<redacted>/test?op=CREATE&data=true&overwrite=true&createparent=true&user.name=<redacted> HTTP/1.1
Host: hadoop-host:50070
User-Agent: Go-http-client/1.1
Content-Length: 5
Content-Type: application/octet-stream
Accept-Encoding: gzip

<BODY>



HTTP/1.1 401 Authentication required
Date: Mon, 06 May 2019 18:32:47 GMT
Date: Mon, 06 May 2019 18:32:47 GMT
Pragma: no-cache
X-FRAME-OPTIONS: SAMEORIGIN
WWW-Authenticate: Negotiate
Set-Cookie: hadoop.auth=; Path=/; HttpOnly
Content-Length: 0



PUT /webhdfs/v1/user/<redacted>/test?op=CREATE&data=true&overwrite=true&createparent=true&user.name=<redacted> HTTP/1.1
Host: hadoop-host
User-Agent: Go-http-client/1.1
Content-Length: 5
Authorization: Negotiate <TOKEN>



HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: close
```


We can see that there no body into the PUT sent after the negotiate

**Comment by jcmturner** [comment] 2019-05-18 06:42
Hi, I think I have resolved this in v7.2.4

Please let me know if this fixes things for you.

**Comment by jcmturner** [comment] 2019-05-31 15:49
@aleproust are you able to confirm if v7.2.4 fixes your issue?

**Comment by jcmturner** [comment] 2019-06-15 14:36
@aleproust I assume this is resolved for you so I'm going to close this issue. Let me know if this is not resolved.

**Closed by jcmturner** 2019-06-15 14:36 UTC
Labels: bug
