### ISSUE TITLE
SPNEGOKRB5Authenticate doesn't respect given service.KeytabPrincipal

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [jcmturner/gokrb5#330] opened 2019-11-06 20:24 UTC
I may be using this library incorrectly, but it appears that the `SPNEGOKRB5Authenticate` function doesn't respect the `service.KeytabPrincipal` given. Please let me know if I should be using the library differently. Thank you in advance for all your work on this library!

## Steps to reproduce
1. Add the following test to `spnego/http_test.go`:
```
func TestSPNEGOKRB5AuthenticateRespectsKeytabPrincipal(t *testing.T) {
	t.Parallel()

	b, err := hex.DecodeString(testGSSAPIInit)
	if err != nil {
		t.Fatalf("Error converting hex string test data to bytes: %v", err)
	}
	b64 := base64.StdEncoding.EncodeToString(b)

	configuredKt := keytab.New()
	buf := bytes.NewBuffer(nil)
	logger := log.New(buf, "", 0)
	handler := SPNEGOKRB5Authenticate(nil, configuredKt, service.KeytabPrincipal("expected-principal"), service.Logger(logger))

	header := make(map[string][]string)
	header[HTTPHeaderAuthRequest] = []string{"Negotiate " + b64}
	handler.ServeHTTP(&httptest.ResponseRecorder{}, &http.Request{
		Header:           header,
		RemoteAddr:       "127.0.0.1:1234",
	})
	// Note that the resulting log line doesn't state it's looking for "expected-principal" in the keytab.
	fmt.Println(buf.String())
}
```
2. On running the test, observe that the following log line has been outputted:

>127.0.0.1:1234 - SPNEGO validation error: defective token detected: [Root cause: Decrypting_Error] Decrypting_Error: error decrypting encpart of service ticket provided: KRB Error: (45) KRB_AP_ERR_NOKEY Service key not available - Could not get key from keytab: matching key not found in keytab. Looking for [HTTP host.test.gokrb5] realm: TEST.GOKRB5 kvno: 2 etype: 18

3. Note that the output above states the code is looking for `host.test.gokrb5` and not `expected-principal` as given.

**Comment by jcmturner** [comment] 2020-01-01 15:20
Hi, this is a duplicate of #275.

It will require a change to the API and therefore a major version revision.

**Closed** 2020-01-31 19:34 UTC
Labels: bug, duplicate, major version iteration
