### ISSUE TITLE
explicitly tagged member didn't match

### ISSUE THREAD

**Issue by bwmarrin** [jcmturner/gokrb5#310] opened 2019-08-07 16:58 UTC
I'm trying to build a web service where the enduser can login via their Active Directory credentials.

I've started with the httpServer.go example, and modified it to use a keytab I generated on the domain controller.

When I try to access the site via Chrome, it does ask for me to enter my username/password and after that I get the below error message from the Go web service.

```
SPNEGO error in unmarshaling SPNEGO token: not a valid SPNEGO token: asn1: structure error: explicitly tagged member didn't match
```

I noticed someone else had this error before in https://github.com/jcmturner/gokrb5/issues/51 but I'm not sure if that issue is related to this or not.

This is my first time using this library so it's likely I've done something wrong.  Are there any additional steps I need to take beyond my simple modification of the httpServer.go example?

**Comment by bwmarrin** [comment] 2019-08-07 19:45
Okay, so I've made some progress.

I added the site I'm connecting to as a intranet site in the Internet Options security tab.  I figured this would be needed for it to work without prompting, but when doing this same thing using Apache, it works with prompting even without the site listed here.

This got me past this error, and I slammed right into another error :

```
SPNEGO validation error: defective token detected: OID of MechToken does not match the first in the MechTypeList
```

Looks like there's an existing issue for this so I'll add to that https://github.com/jcmturner/gokrb5/issues/278


So.. I still think there's an issue here, as it shouldn't this still work without listing the site in the local Intranet listing? Shouldn't it just prompt for username/password and then connect or is that not supported?

**Comment by jcmturner** [comment] 2019-11-23 15:12
Hi, yes I think this is a duplicate of #278 so I’m going to close this one so please follow #278. Thanks.

**Closed by jcmturner** 2019-11-23 15:12 UTC

**Comment by bwmarrin** [comment] 2019-11-23 16:48
This is separate from #278 

When using Apache Kerberos auth - it will first try the kerberos handshake where you don't have to enter a password.  If that fails, it will fall back to allowing the user to enter their username and password and if correct values are provided, it passes authentication details.

Is it possible to fallback to accepting username/password during authentication attempts when SPNEGO fails?

**Comment by NogerbekNurzhan** [comment] 2019-11-27 10:53
@bwmarrin I notice the same error! How you solve it?

**Comment by bwmarrin** [comment] 2019-11-27 14:39
@NogerbekNurzhan  check out ticket https://github.com/jcmturner/gokrb5/issues/278 that is tracking this issue.

There is a PR that seems to fix the issue but @jcmturner  hasn't had time yet to test it thoroughly.

I applied the PR to a fork and am using that for now.
